- name: Create poll directory
  become: true
  file:
    path: /var/www/poll
    state: directory

- name: Extract poll.tar
  become: true
  ansible.builtin.unarchive:
    src: poll.tar
    dest: /var/www/poll/

- name: Install pip
  become: true
  apt:
    name:
      - python3-pip

- name: Install requirement for poll
  ignore_errors: true
  pip:
    requirements: /var/www/poll/requirements.txt

- name: Set service
  become: true
  ansible.builtin.template:
    src: ./poll.j2
    dest: /etc/systemd/system/poll.service
    mode: '0644'

- name: Start Service
  become: true
  ansible.builtin.service:
    name: poll.service
    state: started
